inherit: "config/base.yaml"

multicamera:
  enabled: true
  cameras: 2  # Number of cameras to use
  initialize_all: false  # If true, all cameras initialize independently; if false, only first camera initializes world
